### ISSUE TITLE
Telescopes and ties

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#3763]
Now that people are tying everything and anything to belts and toolstraps, any chance tied telescopes can be added to ;astrology and ;walkingastro?

~Gab

**Comment by jayRyan24** [comment]
This is really a lot more difficult than it sounds. I can do it fairly easy, but the main issue is that it will break people that haven't updated their yamls. Trying to support this and the old way in a clean way is actually quite difficult.

**Comment by jayRyan24** [comment]
I can push the changes and just let the PR stand where it is though, but I am not up for catering to people.

**Comment by jayRyan24** [comment]
Was added, and easier than I first looked.

**Comment by jayRyan24** [comment]
Hi @drgabellia. I've added support for this. Common-moonmage was updated with this support, and walkingastro is currently using it. Astrology.lic will use it once people have a chance to update the common-moonmage files. You can actually bring in astrology.lic to your own files if you want to begin using it. It's here: #3850. You can mark this issue resolved now. 

Thanks!

**Comment by drgabellia** [comment]
How do I need to set it up in my yaml?

**Comment by drgabellia** [comment]
Set it up in my yaml this way:
telescope_storage:
  container: enchanter's toolbelt
  tied: true

But walkingastro didn't work:
[walkingastro]>get my telescope
You should untie the ivory telescope from the enchanter's toolbelt first.

**Comment by jayRyan24** [comment]
There was a bug I couldn't find without a tie to test with, someone else found it and the PR is in for it! Will be in as soon as they get it through!

```
telescope_storage:
container: enchanter's toolbelt # Not needed if tied
tied: <name of thing to tie to>
```

**Comment by drgabellia** [comment]
Set up my toolbelt per your suggestion:
telescope_storage:
  tied: enchanter's toolbelt
Still getting this error:
[walkingastro]>get my telescope
>
You should untie the ivory telescope from the enchanter's toolbelt first.

**Comment by jayRyan24** [comment]
Can you close this, it's completed.

**Comment by jayRyan24** [comment]
@drgabellia

**Comment by jayRyan24** [comment]
> Set up my toolbelt per your suggestion:
> telescope_storage:
> tied: enchanter's toolbelt
> Still getting this error:
> [walkingastro]>get my telescope
> 
> > 
> 
> You should untie the ivory telescope from the enchanter's toolbelt first.

Can you post issues you find to slack, it's easier that way, thanks!
